export const STORE_INFO = {
  name: "INDEXES STORE | متجر إندكس",
  tagline: "PREMIUM QUALITY",
  phone: "967771370740",
  whatsappNumber: "967771370740",
  formattedPhone: "+967 771 370 740",
  address: "صنعاء - شارع حدة - اليمن",
  freeShippingThresholdYER: 30000,
  governorates: [
    "أمانة العاصمة (صنعاء)",
    "محافظة صنعاء",
    "عدن",
    "تعز",
    "إب",
    "الحديدة",
    "حضرموت (المكلا/سيئون)",
    "ذمار",
    "عمران",
    "صعدة",
    "حجة",
    "البيضاء",
    "أبين",
    "لحج",
    "شبوة",
    "المهرة",
    "مأرب",
    "الجوية",
  ],
};
